---
- hosts: '{{ hosts }}'
  tasks:
    - name: destroy all kolla containers
      shell: '{{ item }}'
      ignore_errors: yes
      with_items:
        - docker '{{ destroy_type | default("kill") }}' $(docker ps -a | grep '{{ prefix }}' | awk '{print $1}')
        - docker rm $(docker ps -a | grep '{{ prefix }}' | awk '{print $1}')
