---
- hosts: '{{ hosts }}'
  tasks:
    - name: destroy kolla containers
      shell: '{{ item }}'
      ignore_errors: yes
      with_items:
        - docker kill $(docker ps -a | grep '{{ prefix }}' | awk '{print $1}')
        - docker rm $(docker ps -a | grep '{{ prefix }}' | awk '{print $1}')
